### ISSUE TITLE
Patient Notes History/Attribution

### ISSUE THREAD

**Issue by ph1l** [ph1l/ocemr#19]
Devise some way to discern the history and attribution of patient notes rather than have a free form text area that anyone can edit.

> Another thing is that it would be nice to know who entered information
> into the "Notes" tab, since it's an editable box, not sure how you'd
> be able to do that, but one of the previous teams had some people
> writing all sorts of non-applicable things there (in the wrong place)
> and it's hard figuring out who wrote them.

**Comment by kzcbum** [comment]
correct. it's just not being oriented appropriately to new system users, so they're adding garbage data to the tab. or putting important visit follow-up data that should be printing out but isn't since they put it in the private Notes tab. maybe a subtitle for this tab could be added? ie. "this tab is for internal communication only, does not print out on patient's visit notes."   ?
